apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    orgId: 1
    url: http://influxdb:8086
    basicAuth: false
    editable: true
    jsonData:
      version: Flux
      organization: rabbit
      defaultBucket: rabbit
    secureJsonData:
      token: rabbit
